@startuml "Account Compromised Playbook - Identification"

title "Account Compromised Playbook\n-\nIdentification\n"

partition "Identification" {

start

:[AD1]\nAlerts / Notifications;
note
  Alerts
    - Tickets
    - SIEM
    - AV / EDR Alerts
    - Reports (DNS / Web Proxy / ...)
  Notifications
    - From users
    - From recipients
    - ISP
    - 3rd party
    - Mail provider
    - Computer is slow / crash unexpectedly
endnote

:[AD2]\nIdentify Risk Factors;
note
  Common
    - Credential theft
    - Malware delivery
    - Criminal activities
      - Financial losses
      - Blackmail / Ransom
  Organization specific
    - Reputation damage
    - Financial losses
      - Lost contract / renewal
      - Lower bid to our clients
      - Fines (regulation)
endnote

:[AD3]Data Collection;
note
  - Threat
    - Bitcoin address
    - Email
  - File
    - Hash
    - Reputation
    - Extention type
    - Behavior
  - Domain
    - Reputation
    - Registrar
    - Owner
    - DNS records
    - Multi stage / Redirect
    - Technogies
      - Wordpress
      - Joomla
      - ... 
  - IP
    - Reputation
    - vhosts
endnote

:[AD4]Triage;
note
  - Determine impact
    - Is the malware destroying things?
    - Is the malware proliferating / infecting
      other hosts?
    - Financial impact?
    - BSoD
    - ...
  - Determine Scope
    - No. of hosts received the file
    - No. of hosts that attempt to connect to the URLs
    - No. of hosts with registry keys
    - Other IOC
  - Send Communication
  - Determine if False Positive
endnote

#pink:if ([AD5]\nFalse Positive?) then (yes)
  :Document the findings;
  :Close case;
  end
else (no)
endif

:[AA1]\nVerify;

note
  - Double check previous data
  - Rule out False Positive
endnote

:[AA2]\nList of affected credentials;

note
  - Collect list of affected accounts
endnote

:[AA3]\nLevel of Access / Privielges;

note
  - Access to customers
  - Access to internal
  - What is the access level?
    - Local admin
    - Cloud admin
    - Local user
    - Domain user
  - Account type
    - User
    - Service account
    - API keys
    - Other
endnote

#pink:if ([AA4]\nCritical incident?) then (yes)
  group Critical Playbook
    :Critical Playbook;
  endgroup
else (no)

endif

#pink:if ([AA5]\nDomain Compromised?) then (yes)
  :[AA6]\nDisable turst with infected domain;
  note
    - The infected domain msut be 
      cut off from any other environment
  endnote
else (no)
endif

#pink:if ([AA7]\nLive threat actor?) then (yes)
  :[AA8]\nMonitor all systems closely;
  note
    - In case of a live actor we have to 
      take coordonated  efforts to cut ALL 
      the actor's access at the same time
  endnote
else (no)
endif

#pink:if ([AA9]\nDo We have backups?) then (yes)
  :[AA10]\nEnsure backups are protected;
  note
    - Disable future backups
      - Disalbe backup interface
      - Stop backup scheduling
    - Make an offline copy of the backup
  endnote
else (no)
endif

:[AA11]\nLog Analysis;
note
  - Failed login
  - Successful login
  - Lateral movement
  - Other
endnote

#pink:if ([A12]\nPassword Reused?) then (yes)
  :[AA13]\nUpdate scope;
else (no)
endif

#pink:if([A14]\nTOTP stored in password manager?) then (yes)
  :[AA15]\nUpdate scope;
else (no)
endif

#pink:if ([A15]\nMFA compromised?) then (yes)
  :[AA17]\nUpdate scope;
else (no)
endif

#pink:if ([AA18]\nData exfiltration?) then (yes)
  group "DLP playbook"
    :DLP playbook;
  endgroup
else (no)
endif

#pink:if ([AA19]\nAll affected accounts and domain identified?) then (no)
  :[AA20]\nUpdate scope;
  note
    Update lists of affected:
      - Data
      - Endpoints
      - Company entities
      - Clients
  endnote

  :[AA21]\nScope Validation;
  note
    - New signs of data encrypted
    - Search customers environment
    - Search endpoints for IOCs with EDR
    - Search firewall/proxy/DNS logs for IOCs
  endnote

  :Go back to [AA1];
  end
else (yes)
endif

if ([AA22]\nDo we need external help?) then (yes)
  if ([AA23]\nDo we need technical help?) then (yes)
    :[AA24]\nContact IR professional services;
  else (no)
  endif

  if ([AA25]\nDo we need legal help?) then (yes)
    :[AA26]\nContract Breach Coach;
  else (no)
  endif
else (no)
endif

:[AA27]\nRoot Cause Analysis;
note
  - Phishing?
  - Vishing?
  - Vulnerability?
    - RCE / XSS / LFI ...
  - Remote Service
    - Weak password
    - Brute force
    - Vulnerability
  - Public facing services w/o MFA
endnote

:[AA28]\nSend Communication;
note
  - Internal security teams
  - Affected clients
  - Any internal teams needs
    for remediation or conselling
endnote

}

partition "Containment & Eradication" {

}

@enduml